{% set version = "0.1.5" %}

package:
  name: perl-atlas-modules
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/perl-atlas-modules/archive/{{ version }}.tar.gz
  sha256: df81a9327e1f6028eaa84e7ff31ca4900d0e468e0d96e2f367278043941853e0

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0

requirements:
  host:
   - perl =5.26.2
   - perl-app-cpanminus

  run:
   - perl =5.26.2
   - perl-array-compare
   - perl-app-cpanminus
   - perl-base
   - perl-carp
   - perl-data-dumper
   - perl-data-compare
   - perl-datetime
   - perl-datetime-format-strptime
   - perl-date-format
   - perl-dbi
   - perl-dbd-pg
   - perl-archive-extract
   - perl-clone
   - perl-mime-lite
   - perl-json-parse
   - perl-list-util
   - perl-list-moreutils
   - perl-log-log4perl
   - perl-lwp-simple
   - perl-lwp-protocol-https
   - perl-moose
   - perl-path-tiny
   - perl-tie-ixhash
   - perl-readonly
   - perl-file-spec
   - perl-text-csv
   - perl-json
   - perl-xml-simple
   - perl-xml-parser
   - perl-xml-writer
   - perl-ipc-cmd
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}

test:
  imports:
    - Atlas::AtlasAssayFactory
    - Atlas::FPKMmatrix
    - Atlas::Assay
    - Atlas::ZoomaClient
    - Atlas::Magetab4Atlas
    - Atlas::ExptFinder
    - Atlas::Common
    - Atlas::AtlasConfig::AssayGroup
    - Atlas::AtlasConfig::Analytics
    - Atlas::AtlasConfig::FactorsConfigFactory
    - Atlas::AtlasConfig::ExperimentConfig
    - Atlas::AtlasConfig::Reader
    - Atlas::AtlasConfig::BiologicalReplicate
    - Atlas::ZoomaClient::MappingResult
    - EBI::FGPT::Config


about:
  home: https://github.com/ebi-gene-expression-group/perl-atlas-modules
  license: GPL-3
  summary: A package exporting in-house perl functions and classes used in the data production of EMBL-EBI Expression Atlas data.

extra:
  recipe-maintainers:
    - suhaibMo
