{% set version = "1.0.0" %}

package:
  name: atlas-gene-annotation-manipulation
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-gene-annotation-manipulation/archive/v{{ version }}.tar.gz
  sha256: 3849ad0108332c3611f7d543401139432c56c121811a20b3371cd20b1b61f57c

build:
  number: 0

requirements:
  build:
  host:
  run:
    - r-plyr
    - r-base
    - r-optparse
    - bioconductor-rtracklayer
    - bioconductor-biostrings

test:
  commands:
    - gtf2featureAnnotation.R -h 

about:
  home: https://github.com/ebi-gene-expression-group/atlas-gene-annotation-manipulation 
  license: Apache-2.0
  summary: Scripts for manipulating gene annotation 
  license_family: Apache

