{% set version = "0.0.4" %}

package:
  name: atlas-bash-util
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-bash-util/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 789f91e541825c16d2faf712924afb8528e2eff8a13130a8a49990c322fccd25

build:
  number: 0

requirements:
  build:
  host:
  run:
    - bash

test:
  commands:
    - which atlas-bash-util

about:
  home: https://github.com/ebi-gene-expression-group/atlas-bash-utils
  license: GPL-3
  summary: Generic Bash functions used to build Expression Atlas
  license_family: GPL3
