{% set version = "0.1.4" %}

package:
  name: atlas-bash-util
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-bash-util/archive/refs/tags/v{{ version }}.tar.gz
  sha256: eae64d8afd3192f7c80ac86a3cfa004ce46997fbec2f15fbb50f1674e76c6338

build:
  number: 0
  noarch: generic

requirements:
  build:
  host:
  run:
    - coreutils
    - bash
    - grep

test:
  commands:
    - which atlas-bash-util

about:
  home: https://github.com/ebi-gene-expression-group/atlas-bash-utils
  license: GPL-3
  summary: Generic Bash functions used to build Expression Atlas
  license_family: GPL3
