{% set version = "0.2.4" %}

package:
  name: atlas-bash-util
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-bash-util/archive/refs/tags/v{{ version }}.tar.gz
  sha256: abee5c1f967548e0b7cce9200ed8c13acffa32c93b2aa4618c01dabb253bb8fa

build:
  number: 0
  noarch: generic

requirements:
  build:
  host:
  run:
    - coreutils
    - bash
    - grep

test:
  commands:
    - which atlas-bash-util

about:
  home: https://github.com/ebi-gene-expression-group/atlas-bash-util
  license: GPL-3
  summary: Generic Bash functions used to build Expression Atlas.
  description: |
     It includes support for LSF and SLURM schedulers.
  license_family: GPL3
