{% set version = "0.0.4" %}

package:
  name: atlas-bash-util
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-bash-util/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 71e3780c51fd0f5a12707e26d6b379c8314fd80356398732ffe9e26183e56bb8

build:
  number: 0

requirements:
  build:
  host:
  run:
    - bash

test:
  commands:
    - which atlas-bash-util

about:
  home: https://github.com/ebi-gene-expression-group/atlas-bash-utils
  license: GPL-3
  summary: Generic Bash functions used to build Expression Atlas
  license_family: GPL3
