{% set version = "0.0.3" %}

package:
  name: atlas-bash-util
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-bash-util/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b4d4817778e4e13a1d67318d2ea6721211964a6e86eae99bb71364a6c7df463b 

build:
  number: 0

requirements:
  build:
  host:
  run:
    - bash

test:
  commands:
    - which atlas-bash-util

about:
  home: https://github.com/ebi-gene-expression-group/atlas-bash-utils
  license: GPL-3
  summary: Generic Bash functions used to build Expression Atlas
  license_family: GPL3
