{% set version = "11.2" %}

package:
  name: atlas-web-sc-cli
  version: {{ version }}

source:
  git_url: https://github.com/ebi-gene-expression-group/atlas-web-single-cell
  git_rev: {{ version }}-cli


build:
  number: 1
  skip: false # [win32]
  noarch: generic

requirements:
  build:
    - openjdk >=11.0.0.0
    - gradle >=7.0.0
  host:
  run:
    - bash
    - bats
    - openjdk >=11.0.0.0

test:
  commands:

about:
  home: https://github.com/ebi-gene-expression-group/atlas-web-single-cell
  license: Apache-2.0
  summary: A minimal Spring Boot wrapper to run Single Cell Expression Atlas tasks from the command line.
  license_family: Apache
