{% set version = "1.7" %}

package:
  name: r-atlas-internal
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/internal-ExpressionAtlas/archive/{{ version }}.tar.gz
  sha256: d24be3d2143b13eafde32874895f3ac00f1ed87b5a6f50f10a62d1a34f869d0a

build:
  number: 0
  skip: true # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - make
  host:
    - r-xml
    - r-yaml
    - r-plyr
    - r-base
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-summarizedexperiment
  run:
    - r-xml
    - r-yaml
    - r-plyr
    - r-base
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-summarizedexperiment

test:
  commands:
    - $R -e "library(ExpressionAtlasInternal)"

about:
  home: https://github.com/ebi-gene-expression-group/internal-ExpressionAtlas
  license: GPL-3
  summary: A package exporting functions and classes used in the representation and analysis of EMBL-EBI Expression Atlas data.
  license_family: GPL3
