{% set version = "1.91" %}

package:
  name: r-atlas-internal
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/internal-ExpressionAtlas/archive/{{ version }}.tar.gz
  sha256: c199832aff77103544a96049d2f3e249b9c8c74f95604aebbd1ccf972f53772f

build:
  number: 0
  skip: true # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:

  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - make
  host:
    - r-xml
    - r-yaml
    - r-plyr
    - r-base >=4.5,<4.6.0a0
    - bioconductor-biobase
    - bioconductor-biocgenerics >=0.56
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-summarizedexperiment
  run:
    - r-xml
    - r-yaml
    - r-plyr
    - r-base >=4.5,<4.6.0a0
    - bioconductor-biobase
    - bioconductor-biocgenerics >=0.56
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-summarizedexperiment

test:
  commands:
    - $R -e "library(ExpressionAtlasInternal)"

about:
  home: https://github.com/ebi-gene-expression-group/internal-ExpressionAtlas
  license: GPL-3
  summary: A package exporting functions and classes used in the representation and analysis of EMBL-EBI Expression Atlas data.
  license_family: GPL3
