{% set name = "atlas-anndata" %}
{% set version = "0.0.1" %}

package:
  name: atlas-anndata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atlas_anndata-{{ version }}.tar.gz
  sha256: 22913f6944946ea92325a57d2bd47e1ae56f2fd321b372bcd25e1aa205160694

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - click
    - cmake <3.20
    - jsonschema
    - python
    - pyyaml
    - scanpy >1.1.2
    - scanpy-scripts >1.1.3
    - snakemake

test:
  imports:
    - atlas_anndata
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/ebi-gene-expression-group/atlas-anndata"
  dev_url: "https://github.com/ebi-gene-expression-group/atlas-anndata"
  license: Apache-2.0
  license_file: LICENSE
  summary: "Tools for anndata generation/ consumption for Expression Atlas"

extra:
  recipe-maintainers:
    - pcm32
    - pinin4fjords
