{% set name = "atlas-anndata" %}
{% set version = "0.1.1" %}

package:
  name: atlas-anndata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atlas_anndata-{{ version }}.tar.gz
  sha256: 50f222d3b75636c21088aa2e086ea8e3c608cc0cea4030b7e5ce03a8cfd9969b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python<3.9
  run:
    - click
    - jsonschema
    - python<3.9
    - pyyaml
    - scanpy-scripts >1.1.5
    - snakemake
    - peppy<0.31.2 
    - pillow>=8.3.2
    - xlrd<2.0
    - cython
    - setuptools-scm

test:
  imports:
    - atlas_anndata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ebi-gene-expression-group/atlas-anndata
  summary: Functions for preparing annData files for experiment inclusion in Single cell Expression Atlas
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pinin4fjords
    - pcm32
