{% set name = "atlas-anndata" %}
{% set version = "0.1.0" %}

package:
  name: atlas-anndata
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atlas_anndata-{{ version }}.tar.gz
  sha256: c3110472112f34016b6f8db4033e076d01ffad17e7a9df5ca3520b897bbe1408

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip<19
    - python<3.9
    - cmake <3.20
  run:
    - click
    - pip<19
    - cmake <3.20
    - jsonschema
    - python<3.9
    - pyyaml
    - scanpy >1.1.2
    - scanpy-scripts >1.1.3
    - snakemake

test:
  imports:
    - atlas_anndata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ebi-gene-expression-group/atlas-anndata
  summary: Functions for preparing annData files for experiment inclusion in Single cell Expression Atlas
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pinin4fjords
    - pcm32
