{% set version = "0.1.0" %}

package:
  name: atlas-fastq-provider
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-fastq-provider/archive/v{{ version }}.tar.gz
  sha256: 6812ffc5f61fd6653af9c6b9fa5e3a485a4185809533adc6a433383aecd104dc

build:
  number: 0

requirements:
  build:
  host:
  run:
    - bash

test:
  commands:
    - fetchFastq.sh -h

about:
  home: https://github.com/ebi-gene-expression-group/atlas-fastq-provider
  license: GPL-3
  summary: A package to provide FASTQs via download or file system linking
  license_family: GPL3

