{% set version = "0.1.1" %}

package:
  name: atlas-fastq-provider
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-fastq-provider/archive/v{{ version }}.tar.gz
  sha256: 18b3b6a1b3f7c62117d7d569bddd5941470d60dbe0570db7dc6fc16d0d8d8b66 

build:
  number: 0

requirements:
  build:
  host:
  run:
    - bash

test:
  commands:
    - fetchFastq.sh -h

about:
  home: https://github.com/ebi-gene-expression-group/atlas-fastq-provider
  license: GPL-3
  summary: A package to provide FASTQs via download or file system linking
  license_family: GPL3

