{% set version = "0.1.12" %}

package:
  name: atlas-fastq-provider
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-fastq-provider/archive/v{{ version }}.tar.gz
  sha256: c693b65270b500c26929056fe9facda6815f6bd0563563754d5effe3303524b3

build:
  number: 0

requirements:
  build:
  host:
  run:
    - bash

test:
  commands:
    - fetchFastq.sh -h

about:
  home: https://github.com/ebi-gene-expression-group/atlas-fastq-provider
  license: GPL-3
  summary: A package to provide FASTQs via download or file system linking
  license_family: GPL3

