{% set version = "0.2.4" %}

package:
  name: atlas-fastq-provider
  version: {{ version }}

source:
  url: https://github.com/ebi-gene-expression-group/atlas-fastq-provider/archive/v{{ version }}.tar.gz
  sha256: ca736078ef86f657674dbf670f72ff1b364af60bb51678a7508640eb4ae6d278 

build:
  number: 0

requirements:
  build:
  host:
  run:
    - bash

test:
  commands:
    - fetchFastq.sh -h

about:
  home: https://github.com/ebi-gene-expression-group/atlas-fastq-provider
  license: GPL-3
  summary: A package to provide FASTQs via download or file system linking
  license_family: GPL3

