{% set version = "36.0.0" %}

package:
  name: atlas-web-bulk-cli
  version: {{ version }}

source:
  git_url: https://github.com/ebi-gene-expression-group/atlas-web-bulk
  git_rev: 36.0.0-cli


build:
  number: 0
  skip: false # [win32]
  # script: conda config --set ssl_verify False

requirements:
  build:
    - openjdk >=11.0.0.0
    - gradle >=7.0.0
  host:
  run:
    - bash
    - bats
    - openjdk >=11.0.0.0

test:
  commands:

about:
  home: https://github.com/ebi-gene-expression-group/atlas-cli-bulk
  license: Apache-2.0
  summary: A minimal Spring Boot wrapper to run (bulk) Expression Atlas tasks from the command line.
  license_family: Apache
