name: Build conda packages upon pull request
on:
  pull_request:
    branches:
      - master

jobs:
  get_changed_folders:  # job 1; # Get changed folders github action, https://github.com/marketplace/actions/get-changed-folders
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }} #ubuntu-latest
    strategy:
      fail-fast: false #  if one of the jobs in the matrix expansion fails, the rest of the jobs will be cancelled
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          environment-file: build-environment.yaml    # Path to the build conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Get master SHA
        id: getsha
        run: echo "::set-output name=base_sha::$(git rev-parse master)"        

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v9.3
        with:
            files: 'recipes'
            base_sha: "${{ steps.getsha.outputs.base_sha }}"

      - name: List all modified recipes
        id: changed-recipes
        run: |
            echo "::set-output name=changed_recipes::$(for file in ${{ steps.changed-files.outputs.all_modified_files }}; do dirname $file; done | sort | uniq | tr '\n' ' ')"

      - name: Do a test build of modified recipes
        run: |
            for recipe in ${{ steps.changed-recipes.outputs.changed_recipes }}; do conda build $recipe; done


