name: Build conda packages upon pull request
on:
  # Trigger the workflow on pull request, but only in braches different than main
  # By default, a workflow only runs when a pull_request's activity type
  # is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword.
  # It should work only with recipes that have changed
  pull_request:
    branches-ignore:
      - main
    # explicit definition of the paths, probably unnecessary - to be removed
    paths:
      - 'atlas-experiment-metadata/**'
      - 'atlas-fastq-provider/**'
      - 'atlas-gene-annotation-manipulation/**'
      - 'cell-types-analysis/**'
      - 'irap-bamutils/**'
      - 'irap-components/**'
      - 'r-atlas-internal/**'
jobs:
  get_changed_folders:  # job 1; # Get changed folders github action, https://github.com/marketplace/actions/get-changed-folders
    name: ${{ matrix.os }})
    runs-on: ${{ matrix.os }} #ubuntu-latest
    strategy:
      fail-fast: false #  if one of the jobs in the matrix expansion fails, the rest of the jobs will be cancelled
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: Stockopedia/get-changed-files@v1
      #- name: Get changed folders github action
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/*.js"   # optional
          foldersOnly: true   # to only include folders in the output
          format: newline     # either json, csv or newline
      - name: Echo
        run: |   # output variable with dirs that changed, one in each line
          echo ${{ steps.get_changed.outputs.changed }}
          ::set-output name=CHANGED_DIRS::${{ steps.get_changed.outputs.changed }}

  build_package: # job 2; build only on changed directories
    needs: [get_changed_folders]
    #if CHANGED_DIRS not empty:
    name: ${{ matrix.os }})
    runs-on: ${{ matrix.os }} # [ubuntu-latest, macos-latest]
    strategy:
        fail-fast: false
        matrix:
          os: ["ubuntu-latest", "macos-latest"]
    # https://github.com/marketplace/actions/build-and-publish-conda-packages-to-anaconda-org
    # here the channel is not so important (dry_run: true), we just want to build the package:
    steps:
      - uses: actions/checkout@v1
      - name: build-conda-package
        uses: MichaelsJP/conda-package-publish-action@v1.0.0
        with:
          subDir: .${{ steps.get_changed.outputs.changed }}  # set up here for directory/ies that have changed. Will it work with more 1 dir?
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN_ATLAS_CONDA }}
          platforms: 'osx-64' # 'osx-64 osx-arm64 linux-32 linux-ppc64 linux-ppc64le linux-s390x linux-armv6l linux-armv7l linux-aarch64'
          override: false
          # dry_run only build the packages without publishing them to conda.
          dry_run: true
