name:  Build and push conda package r-atlas-internal
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        subDir: '.r-atlas-internal'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN_ATLAS_CONDA }}
        platforms: 'all'
        override: true
        dry_run: false
