name: Build conda packages upon pull request
on:
  # Trigger the workflow on pull request, but only for the feature branch.
  # By default, a workflow only runs when a pull_request's activity type
  # is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword.
  pull_request:
    branches:
      - feature
    # explicit definition of the paths, probably unnecessary
    paths:
      - 'atlas-experiment-metadata/**'
      - 'atlas-fastq-provider/**'
      - 'atlas-gene-annotation-manipulation/**'
      - 'cell-types-analysis/**'
      - 'irap-bamutils/**'
      - 'irap-components/**'
      - 'r-atlas-internal/**'
jobs:
  publish:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        subDir: '.*'  # will this work for all subDirs?
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN_ATLAS_CONDA }}
        platforms: 'osx-64 osx-arm64 linux-32 linux-ppc64 linux-ppc64le linux-s390x linux-armv6l linux-armv7l linux-aarch64'
        override: false
        # dry_run only build the packages without publishing them to conda.
        dry_run: true
