name: Build conda packages upon pull request
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  get_changed_folders:  # job 1; # Get changed folders github action, https://github.com/marketplace/actions/get-changed-folders
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }} #ubuntu-latest
    strategy:
      fail-fast: false #  if one of the jobs in the matrix expansion fails, the rest of the jobs will be cancelled
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Get master SHA
        id: getsha
        run: echo "::set-output name=base_sha::$(git rev-parse master)"        

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v9.3
        with:
            files: 'recipes'
            base_sha: "${{ steps.getsha.outputs.base_sha }}"

      - name: List all modified recipes
        id: changed-recipes
        run: |
            echo "::set-output name=changed_recipes::$(for file in ${{ steps.changed-files.outputs.all_modified_files }}; do dirname $file; done | sort | uniq | tr '\n' ' ')"
     
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('build-environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build
          environment-file: build-environment.yml
          python-version: 3.8
          channels: ebi-gene-expression-group,conda-forge,bioconda,defaults
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true

      # For pushes rather than pushes, we'll do an upload to conda at the same time

      - name: Configure for possible Anaconda upload
        id: conda-config
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          conda config --set anaconda_upload yes
          echo "::set-output name=conda_opts:: --user ebi-gene-expression-group --token ${{ secrets.ANACONDA_TOKEN_ATLAS_CONDA }}"

      - name: Print config
        run: |
            conda config --show

      - name: Do a test build of modified recipes
        run: |
            for recipe in ${{ steps.changed-recipes.outputs.changed_recipes }}; do conda build${{steps.conda-config.outputs.conda_opts}} $recipe; done
