name: Build and push conda package r-atlas-internal
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        subDir: '.r-atlas-internal'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN_ATLAS_CONDA }}
        platforms: ['osx-64','osx-arm64','linux-32',linux-ppc64','linux-ppc64le','linux-s390x','linux-armv6l','linux-armv7l',linux-aarch64']
        override: true
        dry_run: false
