name: Build and publish conda packages upon merge
on:
  # Trigger the workflow on pull request, but only for the main branch.
  # By default, a workflow only runs when a pull_request's activity type
  # is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword.
  pull_request:
    branches:
      - main
    types: [closed]
    # explicit definition of the paths, probably unnecessary - to be removed
    paths:
      - 'atlas-experiment-metadata/**'
      - 'atlas-fastq-provider/**'
      - 'atlas-gene-annotation-manipulation/**'
      - 'cell-types-analysis/**'
      - 'irap-bamutils/**'
      - 'irap-components/**'
      - 'r-atlas-internal/**'
jobs:
  get_changed_folders:  # Get changed folders github action, https://github.com/marketplace/actions/get-changed-folders
    name: ${{ matrix.os }})
    runs-on: ${{ matrix.os }} #ubuntu-latest
    strategy:
        fail-fast: false #  if one of the jobs in the matrix expansion fails, the rest of the jobs will be cancelled
        matrix:
          os: ["ubuntu-latest", "macos-latest"]
    steps:
    #- name: Get changed folders github action
    - uses: Stockopedia/get-changed-files@v1
      id: get_changed
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ignore: "**/*.js"   # optional
        foldersOnly: true   # to only include folders in the output
        format: newline     # either json, csv or newline
    - name: Echo
      run: |  # output variable with dirs that changed, one in each line
        echo ${{ steps.get_changed.outputs.changed }}
        ::set-output name=CHANGED_DIRS::${{ steps.get_changed.outputs.changed }}

  publish:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    name: ${{ matrix.os }})
    runs-on: ${{ matrix.os }} #[ubuntu-latest, macos-latest]
    strategy:
        fail-fast: false
        matrix:
          os: ["ubuntu-latest", "macos-latest"]
    # https://github.com/marketplace/actions/publish-conda-package-action
    # This action allows to define our channel
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: publish-to-conda
    - uses: amauryval/publish_conda_package_action@1.1.0
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
       # CondaDir: locate the directory containing your meta.yml, conda_build_config.yaml (...) files
        CondaDir: '.*'  # that have changed with the merge
        # Channels: You can add more channel with a space separator
        Channels: 'ebi-gene-expression-group'
        # Platforms: remove one or more of these platforms
        Platforms: 'osx-64' # 'osx-64 osx-arm64 linux-32 linux-ppc64 linux-ppc64le linux-s390x linux-armv6l linux-armv7l linux-aarch64'
        CondaUsername: ${{ secrets.CONDA_USERNAME }}
        CondaPassword: ${{ secrets.CONDA_PASSWORD }}

  no_publish:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    name: ${{ matrix.os }})
    runs-on: ${{ matrix.os }} #[ubuntu-latest, macos-latest]
    strategy:
        fail-fast: false
        matrix:
          os: ["ubuntu-latest", "macos-latest"]
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merged
