name: Build and publish conda packages upon merge
on:
  # Trigger the workflow on pull request, but only for the main branch.
  # By default, a workflow only runs when a pull_request's activity type
  # is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword.
  pull_request:
    branches:
      - main
    types: [closed]
    # explicit definition of the paths, probably unnecessary
    paths:
      - 'atlas-experiment-metadata/**'
      - 'atlas-fastq-provider/**'
      - 'atlas-gene-annotation-manipulation/**'
      - 'cell-types-analysis/**'
      - 'irap-bamutils/**'
      - 'irap-components/**'
      - 'r-atlas-internal/**'
jobs:
  publish:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        subDir: '.*'  # will this work for all subDirs?
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN_ATLAS_CONDA }}
        platforms: 'osx-64 osx-arm64 linux-32 linux-ppc64 linux-ppc64le linux-s390x linux-armv6l linux-armv7l linux-aarch64'
        override: true
        # dry_run only build the packages without publishing them to conda.
        dry_run: false
    no_publish:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merged
